### ISSUE TITLE
Too many doublet 

### ISSUE THREAD

**Issue by kxxxjo** [statgen/demuxlet#109]
Dear All,

Hi I'm KJ from Korea.
First of all, thanks for developing amazing demultiplexing tool.

I'm currently trying to demultiplex 2 and 3 samples using your demuxlet tool, but I'm encountering an issue regarding doublets.
When we ran demuxlet, the output showed a high number of doublets:
![image](https://github.com/statgen/demuxlet/assets/88973914/744c3621-2908-41a4-a849-3fd2b2d4bf72)

As shown in the image above, our results detected an excessive number of doublets. However, we have verified that our experimental steps for preparing GEMs are accurate and free of issues.

Could you please advise us on why we are getting these results and how we can resolve this issue?

Thank you for your assistance.

Best,
KJ

**Comment by hyunminkang** [comment]
Try looking at the distribution of singlets and if the distribution of matched singlets look reasonable. If genotype is incorrect for some individuals, you will end up having too many doublets.

**Comment by kxxxjo** [comment]
Thanks for the quick reply :)

We have sequenced our WGS with 30x depth. I think 30x is enough for detection of SNP. 
Are you saying the WGS data is wrong?

Thanks!

Best,
KJ

**Comment by hyunminkang** [comment]
I would suspect that (1) there might be sample swaps, or (2) your genotypes are not stringently filtered. Make sure to use only verified SNPs that are found in 1000G (no indels), with low missingness. It is common that using WGS-based SNP calls is a cause of problems if you do not filter genotypes carefully.

**Comment by kxxxjo** [comment]
Thanks for your useful feedbacks!

We will let you know after trying based on your comments.

Thanks.

Best,
KJ
