### ISSUE TITLE
turn off doublet detection

### ISSUE THREAD

**Issue by acwarren** [statgen/demuxlet#11]
Is there a way to just infer sample identity and turn off double detection to save computational cost for experiments with higher numbers of samples?

**Comment by yimmieg** [comment]
hi, is demuxlet slow for you even if you use the —group-list flag?

**Comment by acwarren** [comment]
I am using the --group-list flag, which is helpful - but I have single cells that I expect are from one of 25 samples, but which I would like to test against a possible ~1000 samples - which would be a lot of possible doublet combinations. So the computational cost is not from having larger numbers of cells but from having larger numbers of possible samples

**Comment by yimmieg** [comment]
got it. we currently don't have a way to turn off the doublet detection. could you provide some motivation for why you want to test against a vcf of 1000 samples? if it's to check the accuracy of demuxlet, you can put in the 25 samples in the pool and perhaps an additional set of 25 samples not in the pool.

~jimmie

**Comment by acwarren** [comment]
I was interested in doing it for evaluation of accuracy and because there is a possibility that a sample is mislabeled, so cells may actually be from one of the other 1000 samples.

**Comment by yimmieg** [comment]
ah ok. we will look into supporting turning off doublet detection in the future. for now, we have a few higher order items (tuning for V2 chemistry) that we must look into first.
