### ISSUE TITLE
--alpha does not set up gridalpha[] properly

### ISSUE THREAD

**Issue by wac** [statgen/demuxlet#13]
It appears the assumption in the code is that gridAlpha[0] = 0.0.  When using --alpha to set the alpha values, you will need to do 

--alpha 0.0 --alpha 0.5 

Otherwise doublet detection is broken. Just doing

--alpha 0.5

(as recommended in the help) causes no alpha values to ever be tested for doublets (the first alpha value never gets tested for doublets).  Probably need to check/enforce gridAlpha[0]=0.0.

Symptom is getting very weird doublet calls since jBest, kBest end up being set to -1.

Current workaround is to make sure you always use --alpha 0.0 before specifying the actual alpha values you want to test.

**Comment by yimmieg** [comment]
thanks, we have updated the help to reflect this.
