### ISSUE TITLE
Different results for the tutorial

### ISSUE THREAD

**Issue by davetang** [statgen/demuxlet#23]
Hello,

firstly, thank you for the tool. I was going through the tutorial and I get quite different results using the Docker instance and a version of demuxlet (554834481bed7bc3b6ea0b42f9b04c42d5e2169f) compiled on our server.

Using the Docker instance, there are 458 singlets and 42 doublets.

```
docker run -v /Users/dtang/data/demuxlet.tutorial/:/data yimmieg/demuxlet --sam /data/jurkat_293t_downsampled_n500_full_bam.bam --vcf /data/jurkat_293t_exons_only.vcf --field GT --out data/jurkat_293t_demuxlet

cat jurkat_293t_demuxlet.best | cut -f6 | cut -f1 -d'-' | sort | uniq -c
   1 BEST
  42 DBL
 458 SNG
```

However, using the version compiled on the server gives 494 singlets and 6 doublets.

```
demuxlet --sam jurkat_293t_downsampled_n500_full_bam.bam --vcf jurkat_293t_exons_only.vcf --field GT --out jurkat_293t_demuxlet

cat jurkat_293t_demuxlet.best | cut -f6 | cut -f1 -d'-' | sort | uniq -c
      1 BEST
      6 DBL
    494 SNG
```

Should I be concerned?

Cheers,

Dave

**Comment by hyunminkang** [comment]
I think this is because the default alpha parameter have been changed. This should not be a concetn, and we will try to update the documentation accordingly
