### ISSUE TITLE
vcf file with all individual information for a pooled sample

### ISSUE THREAD

**Issue by x811zou** [statgen/demuxlet#26]
Hi! In the demuxlet paper, I did not find the place commenting on how did you make the .vcf file for the 8 individuals. Could you specify it a bit? Thanks!

**Comment by HichamAffia** [comment]
@x811zou Hi, did you find a way? I have a sample containing cells from different individual (singlecell RNA seq). I wonder if my vcf output run on the bam file while contain several genotypes or one hybride genotype? Thanks!

**Comment by hyunminkang** [comment]
Not sure what you're talking about, but you need an external genotype data.

**Comment by HichamAffia** [comment]
Thanks for the answer, my question is can I run the variant call on a bam file containing sequences from 3 individuals? Will the VCF file output have 3 different variant profile or one hybrid profile. Sorry if the question was confusing, hope it clarifies!

**Comment by hyunminkang** [comment]
You need VCF file from SNP array (typical), or you could use VCF from
sequence data, but focus on polymorphic sites in 1000G with MAF >1% or so
focusing on exome regions to avoid false positives.

**Comment by HichamAffia** [comment]
We may consider a SNP array in the future, but that would not be soon enough. If I could just ask for further clarification, what if my individuals are not in the 1000G. I should be able to build my own VCF from my sequencing data.
I also have the BAMs for the the individual from sample that were not pooled and from which I could create differents VCF files. Can I feed demuxlet different vcf file or could I just merge them? Thanks!

**Comment by kmuench** [comment]
Hello, I think I have this issue as well. I have a single 10x .bam file, which contains 5 multiplexed samples, and then five different .vcf files (one for each of the samples, generated through GATK from RNA-Seq data). Should we use something like [GATK's CombineVariants](https://software.broadinstitute.org/gatk/documentation/tooldocs/3.8-0/org_broadinstitute_gatk_tools_walkers_variantutils_CombineVariants.php) to make these 5 files into 1 .vcf file? Or is there a different, preferred technique?

**Comment by HichamAffia** [comment]
Yes you should merge them for demuxlet, I used monovar successfully, but that is for single cell, it’s a wrap that uses samtools.

**Comment by fangfang0906** [comment]
> Hello, I think I have this issue as well. I have a single 10x .bam file, which contains 5 multiplexed samples, and then five different .vcf files (one for each of the samples, generated through GATK from RNA-Seq data). Should we use something like [GATK's CombineVariants](https://software.broadinstitute.org/gatk/documentation/tooldocs/3.8-0/org_broadinstitute_gatk_tools_walkers_variantutils_CombineVariants.php) to make these 5 files into 1 .vcf file? Or is there a different, preferred technique?

Hi, I have the same issue. Could I know how to generate different vcf files using the single merged bam file? Thank you!
