### ISSUE TITLE
VCF file to reproduce "Multiplexing droplet-based single cell RNA-sequencing using natural genetic barcodes" analysis.

### ISSUE THREAD

**Issue by Chynoki** [statgen/demuxlet#5]
Hello,
I'm Sébastien Nin, currently working in the Centre d'Immunologie de Marseille Luminy in France.
I would like to use demuxlet to enable the multiplexing of single-cell RNA-seq samples. In order to do this, I did the tutorial and I found it very good built. To continue my practice with this tool, I would like to reproduce the analysis that can be found in the paper "Multiplexing droplet-based single cell RNA-sequencing using natural genetic barcodes". I already found the bam files on GEO but I can't find the vcf file you used.
Can you advise me on the way I can get the vcf file?

Have a nice day,
Best regards,

Sébastien

**Comment by yimmieg** [comment]
in order to keep this repo small, we put the vcf for reproducing the results in the paper here:

https://github.com/yelabucsf/demuxlet_paper_code/tree/master/fig1
