### ISSUE TITLE
Can this tool be applicable for scRNAseq data from C57BL/6 mouse inbred strains ?

### ISSUE THREAD

**Issue by zh542370159** [statgen/demuxlet#6]
As far as I know，C57BL/6 mouse inbred strain has few SNPs. This may lead to the homogeneous of genomic SNPs in this mouse strain. 
**Could it be possible that we can use Demuxlet to recover the sample identity of a cell in a mixed pool of cells from several C57BL/6 mice?**

**Comment by yimmieg** [comment]
Not really. You need the individuals to be genetically distinct.

**Comment by sejiro** [comment]
What about in the case of using male vs female as samples multiplexed in a lane?

**Comment by hyunminkang** [comment]
Currently it does not support.
-----------------------------------------------------
Hyun Min Kang, Ph.D.
Associate Professor of Biostatistics
University of Michigan, Ann Arbor
Email : hmkang@umich.edu

**Comment by kmshort** [comment]
Any updates on male vs female capability?
