### ISSUE TITLE
how to make GL/GP from SNP array data

### ISSUE THREAD

**Issue by hongsilv** [statgen/demuxlet#81]
Hello, I'm Sungeun from SNUH, Seoul, South Korea.
I first want to say thank you for the great software!

While data processing, I  was having problem with processing input vcf file.
I have a SNP array data, and I'm not sure how I can make a vcf file with GL/GP from it.
Can you recommend any other softwares or methods we can use?

Thanks!

Best regards,
SH

**Comment by hongsilv** [comment]
Actually, I realized that GT is sufficient to run Demuxlet. If I add a flag: --field GT, no errors, run perfectly well.

**Comment by JosefowiczLab** [comment]
> Actually, I realized that GT is sufficient to run Demuxlet. If I add a flag: --field GT, no errors, run perfectly well.

Hi, 
We are planning to use genotype(SNP) array data to demultiplex single-cell RNAseq data. Which platform did you use for the array, and what type of data did you start with? Did you have to convert it into vcf format? In my case, I think I'm going to receive the data as idat format. 

Thanks!
