### ISSUE TITLE
Missing cell barcodes

### ISSUE THREAD

**Issue by jchang97** [statgen/demuxlet#87]
Hi there,

Thank you for this amazing tool!

I am using the output from Cellranger from 10X scRNA-seq and genotyping vcf data using the commands:
demuxlet --sam "/data/gpfs/projects/punim1466/analysis/novaseq/Short_read_VIC01_48hpi_child/outs/possorted_genome_bam_hg19.sorted.bam" --tag-group CB --tag-UMI UB --vcf "/data/gpfs/projects/punim1466/genotyping/child/SNP_genotyping/plink_input/newfile_clean_3_chr_no0_lex.vcf.gz" --field GT --geno-error 0.01 --out Short_read_VIC01_48hpi_child_nowarning_retry --group-list "/data/gpfs/projects/punim1466/analysis/novaseq/Short_read_VIC01_48hpi_child/outs/filtered_feature_bc_matrix/barcodes.tsv.gz"

I've just been looking at my output data and it looks like there are some cell barcodes which are missing (~1-5 barcodes). Is that normal for this to happen? 

For example, in my log file it says: "Finished processing 21128 droplets total" but I will only have 21125 cell barcodes in my output. 

Thank you in advance :)

**Comment by hyunminkang** [comment]
Those barcodes are likely the barcodes that does not have any SNP-overlapping reads.

**Comment by jchang97** [comment]
Okay thank you very much!
