### ISSUE TITLE
How to get VCF file from 10x Genomics 3' gene expression multiplexed library?

### ISSUE THREAD

**Issue by kushalsuryamohan** [statgen/demuxlet#88]
Hello,
We are attempting to do the analysis from your Nature paper on demuxlet (to deconvolute multiplexed samples). The analysis requires a VCF file and I am not quite sure how to get this from 10x 3' gene expression data. Can you please provide more information on how to start from the output of 10x genomics' cellranger count output?

Thanks!

**Comment by hyunminkang** [comment]
You need to have separate DNA genotyping
