### ISSUE TITLE
Consider cleaning up the history of this repository

### ISSUE THREAD

**Issue by Shians** [statgen/demuxlet#9]
This repository is over 600MB in size when it should be significantly smaller.

`du -ha | sort -h`

reveals a very large `.git` folder. Using code from [here](https://stackoverflow.com/questions/10622179/how-to-find-identify-large-files-commits-in-git-history) I see there used to be a large `supplementary.material` folder which no longer exists. I'd suggest you either republish this repository and discard the history or maybe do something with [Github's instructions for removing files](https://help.github.com/articles/removing-sensitive-data-from-a-repository/) and [bfg](https://rtyley.github.io/bfg-repo-cleaner/) to prune away these old files weighing the repository down.

**Comment by yimmieg** [comment]
Hi Shian,

Thank you so much for that suggestion. We have removed the supplementary.material folder from the repo history and created a separate repo for that in case anyone wants to reproduce the figures from our paper.

Best,

~Jimmie
